sudo: false
language: python

python:
  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install pycodestyle

before_script:
    - pycodestyle ./xmapper

script:
    - python setup.py test
